version: "3.7"
 
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./src:/app/src
    expose:
      - '8080'
    ports:
      - "8080:8080"
      # - "8181:8181"
      - "9229:9229"
    command: npm run dev